version: "3.9"
services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app
      - ./requirements.txt:/app/requirements.txt
      - ./.streamlit:/app/.streamlit
    restart: always
